name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up proxy environment variables (optional, uncomment if needed)
      # - name: Set up proxy environment variables
      #   run: |
      #     echo "HTTP_PROXY=http://proxy.example.com:8080" >> $GITHUB_ENV
      #     echo "HTTPS_PROXY=http://proxy.example.com:8080" >> $GITHUB_ENV
      #     echo "NO_PROXY=localhost,127.0.0.1,*.azurecr.io" >> $GITHUB_ENV
      #   if: env.HTTP_PROXY != ''

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug  # Add --http-proxy and --https-proxy if needed
          install: true
          name: mybuilder
          use: true
          bootstrap: true  # Ensure builder is initialized

      # Debug: Verify builder and driver
      - name: Inspect Buildx builder
        run: |
          docker buildx ls
          docker buildx inspect mybuilder --bootstrap
        continue-on-error: true  # Continue to show logs for debugging

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/simple-node-app
          tags: |
            type=raw,value=v${{ github.run_number }}

      # Build and push Docker image with caching
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}  # Reference builder from setup
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/simple-node-app:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/simple-node-app:buildcache,mode=max